spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ""
            client-secret: ""
            scope:
              - email
              - profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"